# Generated by Django 5.0.4 on 2024-06-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrentalhome',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
