# Generated by Django 5.0.4 on 2024-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_rental', '0002_addrentalhome_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrentalhome',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
