# Generated by Django 5.0.4 on 2024-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_rental', '0003_alter_addrentalhome_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrentalhome',
            name='Description',
            field=models.TextField(max_length=100),
        ),
    ]
