# Generated by Django 5.0.4 on 2024-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_rental', '0005_addrentalhome_feature1_addrentalhome_feature2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrentalhome',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
